#!/bin/sh
set -e

if command -v udevadm >/dev/null 2>&1; then
    udevadm control --reload-rules || true
    udevadm trigger --action=add --subsystem-match=tpmrm --sysname-match=tpmrm0 || true
    udevadm trigger --action=add --subsystem-match=misc --sysname-match=uhid || true
fi

exit 0
